### ISSUE TITLE
2.0 examines first 3120 frames and exits

### ISSUE THREAD

**Issue by ShortyCM** [Withenex/vmaf-gui#2] opened 2022-01-16 04:56 UTC
Tried today's release out.  It examines the first 3120 frames and exits
[log.zip](https://github.com/ThatNerdUKnow/vmaf-gui/files/7876402/log.zip)
.

**Comment by ThatNerdUKnow** [comment] 2022-01-16 17:59
How can I reproduce this issue? Could you provide me with the files you are using?

**Comment by ShortyCM** [comment] 2022-01-16 21:48
It doesn't seem to matter which files I use.  I've tried 480p, 1080p, and 4k files and all of them exit after maybe two seconds and all it compares is the first 3120 frames.

**Comment by ThatNerdUKnow** [comment] 2022-01-17 16:55
Try running the program then exiting after it generates the first .y4v files. The progress bar should be at 50%. It's important not to forget this because these files are deleted after the log file is generated. then get a command prompt into the directory you're running vmaf-gui and run the following command `.\vmaf.exe --threads 4 --reference ./temp/source.y4m --distorted ./temp/source.y4m -o log.xml` then post the output from stdout here

**Comment by ShortyCM** [comment] 2022-01-17 17:34
Considering it pretty much instantly pops up the log file that is pretty much impossible to do.  If it is supposed to be creating temporary video files in .\temp then this could be the cause of the issue I'm having.  I've got this installed in a directory under my Program Files (x86) directory.  Normally you would not want to be creating work files in here, as only your application itself should reside there.  In fact, it is probably an admin-rights issue pertaining to the attempt to create these files.  It is probably attempting to create them and failing to do so due to the lack of admin privs, and just running on null data really quickly and then exiting.  Really, you should be attempting to create your temporary files in %temp% rather than .\temp, if that's the case.  Perhaps in %temp%\vmaf-gui\ might be a good idea.  Anyway, if you're creating temporary files then that's my bet as to what's going on here.  I'll test when I'm home.  I'm guessing if I move the program to somewhere else, or fire it up with admin privs, that it will probably start working properly.

FYI, if you're just using ffmpeg to create temporary files to run vmaf on you could actually skip that step and just use the vmaf support that's built into ffmpeg and sidestep having to create temporary files.  This is an example of the command line I've been using to do that:

`ffmpeg -i "distorted.mkv" -i "reference.mkv" -lavfi libvmaf="model_path=vmaf_v0.6.1.pkl:feature=cambi:log_path=distorted.VMAF.txt" -report -f null -`

**Comment by ThatNerdUKnow** [comment] 2022-01-18 19:31
I failed to consider that, I've always been running this program portable rather than installing so I hadn't considered the possibility of permissions issues. It seems an easy enough fix so I should be able to get something out the door

**Comment by ThatNerdUKnow** [comment] 2022-02-01 17:13
> FYI, if you're just using ffmpeg to create temporary files to run vmaf on you could actually skip that step and just use the vmaf support that's built into ffmpeg and sidestep having to create temporary files. This is an example of the command line I've been using to do that:

If i remember correctly ffmpeg doesn't have vmaf built in and you have to download a special build that includes it. I probably won't implement this in this repository since I plan on eventually porting this project to an electron app

**Comment by ShortyCM** [comment] 2022-02-02 05:54
Been doing some testing and it seems that using the stand-alone VMAF util is over three times faster than using ffmpeg anyway.  Only advantage to the built-in ffmpeg method is you don't need the space for the temporary files.

**Comment by ThatNerdUKnow** [comment] 2022-05-04 13:47
Issue may have potentially been fixed in PR #5

**Closed as not planned** 2024-01-28 18:48 UTC
Labels: bug
